version: '3.4'
services:
  prometheus:
    image: prom/prometheus
    user: root
    volumes: 
      - prometheus-data:/prometheus/data
    configs:
      - source: prometheus.yml
        target: /etc/prometheus/prometheus.yml
      - source: alert_rules.yml
        target: /etc/prometheus/alert_rules.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
    ports:
      - "9090:9090"
  alertmanager:
    image: "prom/alertmanager:v0.15.0"
    configs:
      - source: alertmanager.yml
        target: /etc/alertmanager/alertmanager.yml
    ports:
      - 9093:9093
    volumes:
      - alertmanager-data:/alertmanager
  grafana:
    image: grafana/grafana    
    volumes: 
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
  file-handler: 
    image: dockerswarmservice_file-handler:latest
    environment:    
      - NODE_ENV=production
      - port=5672
      - adminPort=15672
      - hostname=rabbit
    ports: 
      - 3401:3401 
  rabbit:
    image: "rabbitmq:3-management-alpine"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "dev_local"
    configs:
      - source: rabbit_enabled_plugins
        target: /etc/rabbitmq/enabled_plugins
    ports:
      - "15671:15672"
      - "5671:5672"
      - "15691:15692"
    volumes: 
      - rabbit-data:/var/lib/rabbitmq/mnesia
  cadvisor:
    image: google/cadvisor:v0.33.0
    volumes:
      - /:/rootfs
      - /var/run:/var/run
      - /sys:/sys
      - /var/lib/docker:/var/lib/docker

volumes:
  grafana-data:  
  rabbit-data:
  prometheus-data:
  alertmanager-data:
configs:
  prometheus.yml:
    external: true
  alert_rules.yml:
    external: true
  alertmanager.yml:
    external: true
  rabbit_enabled_plugins:
    external: true